### ISSUE TITLE
React Native iOS seed - Build fails

### ISSUE THREAD

**Issue by aguerere** [auth0/Mobile-Samples.React#2]
When running the React Native iOS seed, the last build phase fails with an error about "react-native: comand not found" . Turns out this has to do with react-native being installed as recommended in OS X, through node which in itself is installed through nvm. 
The solution is to add the following lines to the "Bundle React Native code and images" Build Phase in the LockReactProject settings:

. ~/.nvm/nvm.sh
nvm use node

before ../node_modules/react-native/packager/react-native-xcode.sh

![react-native-ios-build-error1](https://cloud.githubusercontent.com/assets/14084214/12998702/0d3786c2-d119-11e5-8879-8c47f6d7359f.png)

**Comment by hzalaz** [comment]
This should be fixed with the last version
